apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmChartInflationGenerator:
- chartName: kube-state-metrics
  repo: https://prometheus-community.github.io/helm-charts
  releaseName: ksm
  version: v2.4.2
  namespace: grafana
